RET-3675. Fix application properties
hmcts/et-ccd-callbacks pull request #1035
Opened 2023-07-12 09:20 UTC by Itay-Kirsh

https://tools.hmcts.net/jira/browse/RET-3675
Move defaults for template ids into application.properties and remove duplicates from values.yaml

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-07-14 13:34 UTC, Itay-Kirsh commented
Checked that all templates work and can be called. Doesn't fix all of 3675 but doing it in parts

2023-07-28 14:04 UTC, brendanmchugh approved these changes

2023-07-28 14:13 UTC, JackReevies requested changes

2023-07-28 14:13 UTC, JackReevies commented on config/owasp/suppressions.xml
> +    </suppress>
Is there a reason for suppressing this?

2023-07-28 14:13 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
> +                                                           String username, String linkToExui) {
minor: do we need to pass in CaseDetails now? looks like passing CaseData would suffice

2023-07-28 14:13 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
>          );
Single line now?

2023-07-28 14:13 UTC, JackReevies commented on src/main/resources/application-dev.properties
> -
👌

2023-07-28 15:12 UTC, Itay-Kirsh commented on config/owasp/suppressions.xml
> +    </suppress>
no, undone

2023-08-01 13:49 UTC, JackReevies approved these changes

2023-08-01 14:08 UTC, brendanmchugh approved these changes

2023-08-01 15:29 UTC, merged