RET-4019 Hearing unavailability dates
hmcts/et-ccd-callbacks pull request #1138
Opened 2023-09-05 22:14 UTC by brendanmchugh

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RET-4019

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-09-06 14:38 UTC, lvo700 approved these changes

2023-09-06 16:14 UTC, JackReevies requested changes

2023-09-06 16:14 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingUnavailabilityController.java
> +    @Operation(summary = "About to Submit for bundles respondent")
bundles respondent?

2023-09-06 16:21 UTC, jip1984 approved these changes

2023-09-07 08:24 UTC, brendanmchugh commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingUnavailabilityController.java
> +    @Operation(summary = "About to Submit for bundles respondent")
updated

2023-09-07 09:30 UTC, brendanmchugh commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/HearingUnavailabilityController.java
> +        caseData.setPartySelection(null);
The config is setup to save the unavailability date ranges to a collection for both the respondent and the claimant.

2023-09-07 09:44 UTC, JackReevies approved these changes

2023-09-07 09:45 UTC, merged