RET-4140
hmcts/et-ccd-callbacks pull request #1169
Opened 2023-09-25 21:32 UTC by GauravChawlaMOJ

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RET-4140

### Change description ###

Pre-Hearing deposit callback implementation

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2023-09-26 07:40 UTC, hsjhita commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/admin/prehearingdeposit/PreHearingDepositController.java
> +            throw new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR, "Unable to import staff", e);
change staff to pre hearing deposit data

2023-09-26 07:40 UTC, hsjhita commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/domain/prehearingdeposit/PreHearingDepositData.java
> +    // For adding judge
maybe change this comment

2023-11-13 13:34 UTC, furnivall approved these changes

2023-11-13 13:59 UTC, hsjhita requested changes

2023-11-13 13:59 UTC, hsjhita commented on src/test/resources/PreHearingDepositData.xlsx
Can this file be removed or the data changed please? This is live data and should not be committed to Git

2023-11-13 14:12 UTC, JustMehmet commented on src/test/resources/PreHearingDepositData.xlsx
Changed file content. Thanks Harpreet,

2023-11-13 15:50 UTC, merged