RET-4285: Added CaseFlags and CaseLinking code behind a feature flag
hmcts/et-ccd-callbacks pull request #1247
Opened 2023-10-13 08:40 UTC by JackReevies

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RET-4285

### Change description ###

Added CaseFlags and CaseLinking code behind a feature flag

**Does this PR introduce a breaking change?** (check one with "x")

```
[] Yes
[x] No
```

2023-10-13 09:38 UTC, ss-evoco requested changes
Why have you included case linking into your branch ? It makes it harder to cover everything. 

Also, wasnt there another controller that used case flags before as well ? Something with post in the name ?

2023-10-13 09:38 UTC, ss-evoco commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CaseActionsForCaseWorkerController.java
> +                caseManagementForCaseWorkerService.setCaseNameHmctsInternal(caseData);
Isnt global search doing this else where already ?

2023-10-13 14:32 UTC, ss-evoco submitted a review, later dismissed

2023-10-16 14:59 UTC, marcjudge approved these changes

2023-10-17 08:04 UTC, ss-evoco commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/FeatureToggleService.java
> +    public boolean isCaseFlagsLinkingEnabled() {
Resolving as re-review passed.

2023-10-17 08:11 UTC, lvo700 approved these changes

2023-10-18 09:33 UTC, merged