RET-4528
hmcts/et-ccd-callbacks pull request #1528
Opened 2024-01-18 09:59 UTC by cindychmcts

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/RET-4528

### Change description ###

Auto populate any reasonable adjustments submitted on the ET1 into the relevant section in the ET1 vetting event

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-01-22 13:30 UTC, JackReevies requested changes

2024-01-22 13:30 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
> +        }
Could we use guard clauses here instead?

also `caseData.getClaimantHearingPreference()` and its `getReasonableAdjustments()` is called many times, might be better to extract as a variable.

2024-01-22 13:30 UTC, btensay submitted a review, later dismissed

2024-01-23 09:48 UTC, JackReevies requested changes

2024-01-23 09:48 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
> +        caseData.setEt1ReasonableAdjustmentsTextArea(hearingPreference.getReasonableAdjustmentsDetail());
```suggestion
        Optional.ofNullable(hearingPreference)
                .map(ClaimantHearingPreference::getReasonableAdjustments)
                .ifPresent(reasonableAdjustment -> {
                    caseData.setEt1ReasonableAdjustmentsQuestion(YES.equals(reasonableAdjustment) ? YES : NO);
                    caseData.setEt1ReasonableAdjustmentsTextArea(hearingPreference.getReasonableAdjustmentsDetail());
                });
```

2024-01-23 09:48 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
> +import org.apache.commons.lang3.StringUtils;
```suggestion
```

2024-01-23 09:48 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
> +import org.springframework.util.ObjectUtils;
```suggestion
```

2024-01-23 13:27 UTC, JackReevies approved these changes

2024-01-23 13:45 UTC, jip1984 approved these changes

2024-01-25 11:12 UTC, merged