Ret 4678 - Legal rep access to multiple
hmcts/et-ccd-callbacks pull request #1897
Opened 2024-05-07 09:15 UTC by lvo700

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/RET-4678

### Change description ###

Giving a legal rep access to a multiple.

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-05-17 14:30 UTC, JackReevies requested changes

2024-05-17 16:21 UTC, marcjudge commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignment.java
> +        String caseType = caseDetails.getCaseTypeId() + "_Multiple";
Feel like we might be doing something similar in other places. Might be a good idea to move to a helper

2024-05-17 16:21 UTC, marcjudge commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/CcdCaseAssignment.java
> +            log.info("Error from ccd - {}", exception.getMessage());
Use log.error

2024-05-20 10:25 UTC, JackReevies approved these changes

2024-05-20 11:06 UTC, marcjudge approved these changes

2024-05-20 11:06 UTC, merged