Trim respondentName to remove trailing spaces
hmcts/et-ccd-callbacks pull request #1956
Opened 2024-05-28 10:51 UTC by hsjhita

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-05-28 12:03 UTC, btensay approved these changes

2024-06-24 11:29 UTC, GauravChawlaMOJ requested changes

2024-06-24 11:29 UTC, GauravChawlaMOJ commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3VettingService.java
> +        String respondentName = caseData.getEt3ChooseRespondent().getSelectedLabel().trim();
may be add a test for this?

2024-06-25 10:15 UTC, JackReevies approved these changes

2024-06-25 10:16 UTC, Mike-Brain approved these changes

2024-06-25 11:00 UTC, merged