RET-1838
hmcts/et-ccd-callbacks pull request #304
Opened 2022-06-22 12:24 UTC by cindychmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RET-1838

### Change description ###

Update for handle 0 to 6 number of Acas certs

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-06-22 13:06 UTC, robin-ieong commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
> +        caseDetails.getCaseData().setEt1VettingBeforeYouStart(initialBeforeYouStart(caseDetails));
I don't think this method is required, why not just setEt1VettingBeforeYouStart directly from the controller method?

2022-06-22 13:10 UTC, robin-ieong commented on src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingServiceTest.java
> +        caseDetails.getCaseData().setDocumentCollection(documentTypeItemList);
Can we do the above lines in the @BeforeEach method? Same applies to the next method, that should be able to reduce  duplicated code.

2022-06-22 14:26 UTC, hsjhita commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
> +    public String initialBeforeYouStart(CaseDetails caseDetails) {
private

2022-06-22 14:27 UTC, hsjhita commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et1VettingService.java
>          if (documentCollection != null && !documentCollection.isEmpty()) {
CollectionUtil.isNotEmpty

2022-06-22 14:38 UTC, nickwest1 requested changes
We may need to have a discussion on these comments Cindy.  Possibly a pairing session.

2022-06-23 15:05 UTC, robin-ieong approved these changes

2022-06-23 15:06 UTC, merged