Ret 2019
hmcts/et-ccd-callbacks pull request #338
Opened 2022-07-04 15:07 UTC by Brogie

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-2019

### Change description ###
https://tools.hmcts.net/jira/browse/RET-2019

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[✓] No
```

2022-07-04 15:41 UTC, JackReevies approved these changes

2022-07-05 08:25 UTC, hsjhita commented on src/main/resources/application-dev.properties
> +queue.create-updates.send.connection-string = Endpoint=sb://ethos-servicebus-devs.servicebus.windows.net/;SharedAccessKeyName=SendSharedAccessKey;SharedAccessKey=qSwiG9x7RbndG6ryLw1WYCEUi0dsr4kJeJRpt
this need to be removed

2022-07-05 08:26 UTC, hsjhita commented on src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/Et3VettingControllerTest.java
> +                .header("Authorization", AUTH_TOKEN)
checkstyle and 2 tests below

2022-07-05 08:29 UTC, hsjhita commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelper.java
> +import com.google.common.base.Strings;
checkstyle - import order?

2022-07-05 15:23 UTC, JackReevies approved these changes

2022-07-05 16:28 UTC, nickwest1 commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3VettingHelper.java
>              }
May be neater to extract this into it's own method to avoid too much nesting

2022-07-05 16:29 UTC, nickwest1 commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3VettingService.java
> +            log.error(String.format("Failed to restore et3 data for case %s", caseData.getEthosCaseReference()));
If we log upon an exception, then include the exception in the log

2022-07-05 17:03 UTC, JackReevies approved these changes

2022-07-06 09:17 UTC, nickwest1 requested changes

2022-07-06 09:17 UTC, nickwest1 commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/Et3VettingService.java
> +                caseData.getEthosCaseReference(), e.getMessage()));
Just e, not only the message

I.e.
log.error(String.format("Failed to restore et3 data for case %s",
                caseData.getEthosCaseReference(), e))

2022-07-06 11:02 UTC, nickwest1 approved these changes

2022-07-06 13:25 UTC, merged