Ret 2185 2
hmcts/et-ccd-callbacks pull request #440
Opened 2022-08-30 11:07 UTC by robin-ieong

https://tools.hmcts.net/jira/browse/RET-2185

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-09-01 11:04 UTC, JackReevies approved these changes

2022-09-01 12:38 UTC, nickwest1 requested changes

2022-09-01 13:46 UTC, robin-ieong commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailService.java
> +        }
If I remember correctly Les said in the refinement to ignore that for now but will confirm with him again once he's back. He did say that the email should be validated and hence we have implemented the email validation which will display an error message and ask user to re-enter the email address if it isn't in the right format.

2022-09-01 15:34 UTC, robin-ieong commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/config/NotificationsConfig.java
> +public class NotificationsConfig {
Yes, added.

2022-09-01 15:34 UTC, robin-ieong commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/CreateReferralController.java
> +    public String referralTemplateId;
Yes, refactored.

2022-09-01 15:34 UTC, robin-ieong commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
>  public class ReplyToReferralController {
Added

2022-09-01 15:35 UTC, robin-ieong commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/ReplyToReferralController.java
> +            ReferralHelper.buildPersonalisation(caseData, TRUE.equals(caseData.getIsJudge()), false));
That is actually a string value.

2022-09-01 15:35 UTC, robin-ieong commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelper.java
> +    public static Map<String, String> buildPersonalisation(CaseData caseData, boolean isJudge, boolean isNewReferral) {
added

2022-09-01 15:35 UTC, robin-ieong commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailService.java
> +    public void sendEmail(String templateId, String emailAddress, Map<String, String> personalisation) {
added

2022-09-01 15:35 UTC, robin-ieong commented on src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/ReferralHelperTest.java
> +        assertEquals(errors, ReferralHelper.validateEmail("invalid.email.example"));
Refactored to use the contains method.

2022-09-02 11:12 UTC, robin-ieong commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/EmailService.java
> +        }
As discussed I have changed it to throw a RunTimeException when it fails to send email.

2022-09-02 11:27 UTC, nickwest1 approved these changes

2022-09-02 11:28 UTC, merged