Case Transfer Automation and Refactoring
hmcts/et-ccd-callbacks pull request #695
Opened 2023-02-08 00:01 UTC by SharifChoudhury1

Case Transfer for England/Wales, Case Transfer for Scotland and Case Transfer for ECM

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-02-08 08:31 UTC, dharrisMOJ requested changes

2023-02-08 23:49 UTC, SharifChoudhury1 commented on src/test/end-to-end/pages/steps.js
> -        executeCaseTransfer: steps.caseTransfer.caseTransfer,
Leeds Transfer Deleted

2023-02-09 00:02 UTC, SharifChoudhury1 commented on src/test/end-to-end/pages/caseTransfer/caseTransferScotland.js
> +    I.waitForText('has been updated with event: Case Transfer (Scotland)');
I.click("//div[text()='History']");
    I.see('Case Transfer (Scotland)');

2023-02-09 00:02 UTC, SharifChoudhury1 commented on src/test/end-to-end/pages/caseTransfer/caseTransferECM.js
> +    I.waitForText('has been updated with event: Case Transfer to ECM');
I.click("//div[text()='History']");
    I.see('Case Transfer to ECM');

2023-02-09 11:28 UTC, dharrisMOJ approved these changes

2023-02-09 11:41 UTC, pats-john approved these changes

2023-02-09 15:01 UTC, merged