Ret 2952 - added submitted page to sendNotification
hmcts/et-ccd-callbacks pull request #715
Opened 2023-02-15 17:06 UTC by paul-peasegood

**Before creating a pull request make sure that:**

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-2952

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-02-15 17:08 UTC, JackReevies requested changes

2023-02-15 17:08 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/SendNotificationController.java
> +     * JavaDocs.
JavaDocs

2023-02-15 17:08 UTC, JackReevies commented on src/test/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/SendNotificationControllerTest.java
> +        }
These don't look like the right level of indentation

2023-02-15 17:08 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/SendNotificationController.java
> +            @ApiResponse(responseCode = "500", description = "Internal Server Error")
Are these changes intentional?

2023-02-16 07:24 UTC, ikirsanov approved these changes

2023-02-16 09:59 UTC, JackReevies approved these changes

2023-02-16 10:02 UTC, merged