Ret 2953 added selectNotification
hmcts/et-ccd-callbacks pull request #737
Opened 2023-02-21 17:14 UTC by paul-peasegood

**Before creating a pull request make sure that:**

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-2953

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[] Yes
[x] No
```

2023-02-21 17:57 UTC, JackReevies requested changes

2023-02-21 17:57 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
> +imort java.util.List;
??

2023-02-21 17:57 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
> +
Remove this extra line

2023-02-21 17:57 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
> +
Missing a closing brace here

2023-02-22 14:57 UTC, JackReevies requested changes

2023-02-22 14:57 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationController.java
> +        // Code here
Redundant comment

2023-02-22 14:57 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationController.java
> +    * about to start.
Expand on these javadocs please

2023-02-22 14:57 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationController.java
> +    * About to Submit.
Expand on these javadocs please

2023-02-22 16:46 UTC, JackReevies approved these changes

2023-02-23 09:46 UTC, marcjudge approved these changes

2023-02-23 10:36 UTC, merged