Ret 2954
hmcts/et-ccd-callbacks pull request #782
Opened 2023-03-13 12:00 UTC by paul-peasegood

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-2954

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-03-13 13:48 UTC, JackReevies requested changes

2023-03-13 13:48 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/controllers/RespondNotificationController.java
> +    * midGetNotification.
JavaDocs please

2023-03-13 13:48 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/service/SendNotificationService.java
> +    }
There now exists a helper method for this in `Helper`. Would prefer using this instead of duplicating code

2023-03-14 10:37 UTC, robin-ieong approved these changes

2023-03-14 10:47 UTC, JackReevies approved these changes

2023-03-14 11:55 UTC, merged