Ret 3669 Wrong title on View a Judgement, Order or Notification
hmcts/et-ccd-callbacks pull request #947
Opened 2023-05-23 14:40 UTC by paul-peasegood

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RET-3669

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2023-05-23 14:45 UTC, Itay-Kirsh commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/DocmosisApplication.java
> +        // Hello world
?

2023-05-23 14:46 UTC, Itay-Kirsh commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
> +        if(sendNotificationType.getSendNotificationUploadDocument() == null) {
space after if i think is the convention, nothing major

2023-05-23 14:46 UTC, Itay-Kirsh commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
> +        for(DocumentTypeItem documentTypeItem : sendNotificationType.getSendNotificationUploadDocument()) {
same with for

2023-05-24 08:29 UTC, JackReevies requested changes

2023-05-24 08:29 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/constants/TableMarkupConstants.java
> +    public static final String ORDER_APP_DOC_MARKUP = "|Description  %s|\r\n"
minor: could we choose a better name for this? its not very clear from name alone

2023-05-24 08:29 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
> +                sendNotificationType.getSendNotificationCaseManagement()},
minor: this looks like it could fit on one line

2023-05-24 08:29 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
> +                sendNotificationType.getSendNotificationSelectParties()},
minor: these look like they could fit on one line

2023-05-24 08:29 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
> +            return documents;
minor: why do we need to add a blank entry to the list here?

2023-05-24 08:29 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/PseHelper.java
> +            sendNotificationType.getSendNotificationSelectHearing().getSelectedLabel();
```suggestion
        return Optional.ofNullable(sendNotificationType.getSendNotificationSelectHearing())
            .map(SendNotificationSelectHearing::getSelectedLabel)
            .orElse("");
```

2023-05-24 16:16 UTC, JackReevies approved these changes

2023-05-25 08:57 UTC, Itay-Kirsh approved these changes

2023-05-25 08:57 UTC, merged