RET-3610
hmcts/et-ccd-callbacks pull request #950
Opened 2023-05-24 17:31 UTC by cindychmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RET-3610

### Change description ###

CR - ET3 Response - ability to resubmit an ET3

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-05-25 10:38 UTC, hsjhita approved these changes

2023-05-25 15:36 UTC, hsjhita approved these changes

2023-05-25 15:46 UTC, hsjhita commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
> +                && !YES.equals(respondent.getExtensionResubmitted());
might be worth null check all of these fields

2023-05-30 12:15 UTC, Itay-Kirsh requested changes

2023-05-30 12:15 UTC, Itay-Kirsh commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
> +        if (YES.equals(respondent.getResponseReceived())
Do we not need to null check these here too?

2023-05-30 13:04 UTC, Itay-Kirsh commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
> +        if (YES.equals(respondent.getResponseReceived())
As discussed privately, anything that only needs to be compared with YES.equals doesn't need null checking

2023-05-30 13:05 UTC, Itay-Kirsh commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/helpers/Et3ResponseHelper.java
> +        if (respondent.getExtensionRequested() != null
Also as mentioned in the next (resolved) comment, don't need to null check the values that are only compared with YES.equals later.

2023-05-30 14:07 UTC, Itay-Kirsh approved these changes

2023-05-30 14:09 UTC, merged