RET-3461 - cleaned up method & removed confusing Ternarys
hmcts/et-ccd-callbacks pull request #956
Opened 2023-05-30 10:32 UTC by aaronjduffy

https://tools.hmcts.net/jira/browse/RET-3461

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-06-01 11:22 UTC, JackReevies requested changes
great improvement here! Just one little minor comment

2023-06-01 11:22 UTC, JackReevies commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReport.java
> +        } else {
no need for an else clause here, the return line above will already quit out of this method if `total == 0`

2023-06-01 11:35 UTC, Itay-Kirsh commented on src/main/java/uk/gov/hmcts/ethos/replacement/docmosis/reports/timetofirsthearing/TimeToFirstHearingReport.java
>      private void setPercent(AdhocReportType adhocReportType) {
This isn't tested at all so we really should add tests, verify that they pass on the previous code and on the new code as well.
As it's a private method (being called by other private methods higher up), go to the first public method that indirectly calls this and test it.

2023-06-07 15:49 UTC, Itay-Kirsh approved these changes

2023-06-07 16:10 UTC, merged